/**
 * Piano-roll public types.
 *
 * `PianoRollNote` is the unit of visualization (and, eventually, editing).
 * It is a superset of the flat MIDI events in `@viritura/audio`'s
 * `MidiTimeline`: it carries MNX identity (`locator` + `noteId`) and
 * provenance flags (`fromTie`, `fromRepeat`) so future edit gestures can
 * route patches back to the originating MNX node without re-deriving the
 * mapping by heuristic.
 *
 * The provenance flags are also a *visualization* hint: rectangles whose
 * `fromTie` is true should render as a continuation of the previous note
 * (no attack), and `fromRepeat` rectangles should render slightly faded
 * to indicate they came from a repeat expansion rather than a fresh
 * authored event.
 */

import type { EventLocator } from "@viritura/core";

/**
 * A single note as displayed on the piano roll.
 *
 * One MNX `<event>` containing a chord of N pitches expands to N
 * `PianoRollNote`s sharing the same `locator` but different `noteIndex`
 * and `noteId` values.
 *
 * Tied notes are expanded into multiple `PianoRollNote`s; the
 * continuations carry `fromTie: true` and point at the *continuation*
 * note's locator (so an edit lands on the right MNX node).
 *
 * Notes generated by repeat / jump expansion carry `fromRepeat: true`
 * and point at the *source* event's locator. Edits against these should
 * be disabled in the first cut of the editor — there is no unambiguous
 * way to "edit one repetition" without forking the source event.
 */
export interface PianoRollNote {
  // ── Identity ──────────────────────────────────────────────────────────────
  /** MNX event this rectangle came from. */
  readonly locator: EventLocator;
  /** Index within the event's chord (0 for a single-note event). */
  readonly noteIndex: number;
  /** Stable note id from the MNX model (`YK_ID`). */
  readonly noteId: string;

  // ── Pitch / velocity ──────────────────────────────────────────────────────
  /** MIDI note number (0–127). */
  readonly midiNote: number;
  /** Velocity (0–127). */
  readonly velocity: number;

  // ── Routing ───────────────────────────────────────────────────────────────
  /** Index of the part in `Score.parts`. Drives colouring + filtering. */
  readonly partIndex: number;

  // ── Time (audio) ──────────────────────────────────────────────────────────
  /** Note-on time in seconds, relative to the start of the score. */
  readonly startSeconds: number;
  /** Note-off time in seconds. Duration-aware (respects articulation). */
  readonly endSeconds: number;

  // ── Time (notation) ───────────────────────────────────────────────────────
  /** Measure index (0-based) the note begins in. */
  readonly startMeasure: number;
  /** Beat within `startMeasure` (0-based, quarter = 1). */
  readonly startBeat: number;
  /**
   * Notated duration, expressed as quarter-note fractions
   * (1 = quarter, 0.5 = eighth, 1.5 = dotted quarter, etc.).
   *
   * Kept as a raw number for v1 so the renderer can do trivial math.
   * Once edits land we'll likely promote this to the structured
   * `NoteValue` type from `@viritura/core` for snap-to-grid fidelity.
   */
  readonly notatedDurationQuarters: number;

  // ── Provenance ────────────────────────────────────────────────────────────
  /** True if this rectangle is the continuation half of a tie. */
  readonly fromTie: boolean;
  /** True if this rectangle came from repeat / jump expansion. */
  readonly fromRepeat: boolean;
}

/**
 * Viewport / camera state for the roll.
 *
 * The roll is a Synthesia-style waterfall:
 *
 *   - Horizontal axis = pitch. The full piano (`minMidi`..`maxMidi`) is
 *     always visible; there is no horizontal pan or zoom in v1.
 *   - Vertical axis = time. The keyboard sits at the bottom of the
 *     stage and the playhead is the line directly above it. Notes
 *     scheduled in the future are drawn higher on the canvas and fall
 *     downward as the playhead advances.
 *
 * Only the vertical (time) density is user-adjustable — wheel zoom
 * changes `secondsAhead` so the user can spread upcoming notes out or
 * compress them.
 */
export interface PianoRollViewport {
  /**
   * Seconds of future score-time shown above the keyboard. A larger
   * value means notes appear sooner and fall more slowly.
   */
  readonly secondsAhead: number;
  /** Lowest MIDI note shown (leftmost key). */
  readonly minMidi: number;
  /** Highest MIDI note shown (rightmost key). */
  readonly maxMidi: number;
}

/** Configuration for grid snapping. Computed; not yet enforced. */
export interface PianoRollGrid {
  /** Grid step in quarter notes (e.g. 0.25 = 16th-note grid). */
  readonly stepQuarters: number;
}

/** Selection state for the roll. Keyed by `PianoRollNote.noteId`. */
export type PianoRollSelection = ReadonlySet<string>;
