//! MNX JSON Schema → Rust `raw` types generator.
//!
//! Reads the same `mnx-schema.json` that `pnpm gen:raw` (TypeScript) consumes,
//! runs it through [typify] to produce `serde`-aware Rust structs/enums, and
//! writes the result to `viritura-engine/src/raw.rs`.
//!
//! Also reads `packages/format/schemas/viritura-extensions.json` and emits
//! `viritura-engine/src/raw_viritura.rs` — strongly-typed counterparts for
//! the Viritura `_x.viritura.*` vendor extensions. The promote walker
//! consumes these instead of opaque `serde_json::Value` so schema drift
//! surfaces as a compile error rather than a silent "decoded as None".
//!
//! Run with:
//! ```bash
//! cargo run -p viritura-codegen
//! ```
//!
//! Or via pnpm from the repo root:
//! ```bash
//! pnpm gen:raw:rust
//! ```
//!
//! The generated files are committed. They are not regenerated on `cargo
//! build`.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use schemars::schema::RootSchema;
use serde_json::{json, Value};
use typify::{TypeSpace, TypeSpaceSettings};

/// Resolve a path relative to the workspace root (one level above `engine/`).
fn workspace_path(relative: &str) -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    // CARGO_MANIFEST_DIR points at engine/viritura-codegen/.
    // Repo root is two levels up.
    manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root is two levels above the codegen crate manifest")
        .join(relative)
}

fn main() -> Result<()> {
    generate_mnx_core()?;
    generate_viritura_extensions()?;
    Ok(())
}

/// Generate `raw.rs` from the MNX core schema.
fn generate_mnx_core() -> Result<()> {
    // Source: the canonical MNX schema lives in the format package
    // (this is the same file the TS `pnpm gen:raw` script consumes). Reading
    // from the same source keeps schema, TS raw types, and Rust raw types in
    // lockstep: a single `gen:raw && gen:raw:rust` run produces matching outputs.
    let schema_path = workspace_path("packages/format/schemas/mnx-schema.json");
    let out_path = workspace_path("engine/viritura-engine/src/raw.rs");
    let schema_copy_path = workspace_path("engine/viritura-engine/src/mnx-schema.json");

    println!("[mnx-core] Reading schema:  {}", schema_path.display());
    println!("[mnx-core] Writing types:   {}", out_path.display());
    println!("[mnx-core] Copying schema:  {}", schema_copy_path.display());

    let schema_json = fs::read_to_string(&schema_path)
        .with_context(|| format!("failed to read schema at {}", schema_path.display()))?;

    let mut codegen_schema: Value =
        serde_json::from_str(&schema_json).context("failed to parse MNX schema as JSON")?;
    remove_numeric_constraints(&mut codegen_schema);
    let root_schema: RootSchema = serde_json::from_value(codegen_schema)
        .context("failed to parse MNX schema as schemars::RootSchema")?;

    let mut settings = TypeSpaceSettings::default();
    settings.with_struct_builder(false);

    let mut type_space = TypeSpace::new(&settings);
    type_space
        .add_root_schema(root_schema)
        .context("typify failed to process the MNX schema")?;

    write_typespace(
        &type_space,
        &out_path,
        "// @generated by viritura-codegen from packages/format/schemas/mnx-schema.json.\n\
         // DO NOT EDIT BY HAND. Re-run `pnpm gen:raw:rust` (or `cargo run -p viritura-codegen`).\n\
         //\n\
         // These types are the structural decoding of MNX JSON, before any\n\
         // viritura-extension hoisting. They are the Rust mirror of\n\
         // `packages/format/src/mnx/generated/raw.ts`.\n\n\
         #![allow(\n    clippy::all,\n    clippy::pedantic,\n    clippy::nursery,\n    clippy::cargo,\n    dead_code,\n    non_camel_case_types,\n    non_snake_case,\n    unused_imports,\n    missing_docs,\n)]\n\n",
    )?;

    // Copy the schema next to raw.rs so viritura-engine's validator module
    // can embed it via include_str! without reaching outside the crate.
    fs::copy(&schema_path, &schema_copy_path)
        .with_context(|| format!("failed to copy schema to {}", schema_copy_path.display()))?;

    println!(
        "[mnx-core] Done. {} bytes written.",
        fs::metadata(&out_path)?.len()
    );
    Ok(())
}

/// Numeric bounds are enforced by the unmodified runtime schemas. Omitting
/// them from Typify input keeps primitive wire representations stable and
/// avoids Typify 0.4.3 panics when local bounds accompany a numeric `$ref`.
fn remove_numeric_constraints(value: &mut Value) {
    match value {
        Value::Object(object) => {
            object.remove("minimum");
            object.remove("maximum");
            object.remove("exclusiveMinimum");
            object.remove("exclusiveMaximum");
            for child in object.values_mut() {
                remove_numeric_constraints(child);
            }
        }
        Value::Array(items) => {
            for item in items {
                remove_numeric_constraints(item);
            }
        }
        _ => {}
    }
}

/// Generate `raw_viritura.rs` from the Viritura extensions schema.
///
/// The extensions schema only contains `$defs` (no usable root type), so we
/// synthesise a wrapper root that references each `$def` as a property.
/// typify then emits a named struct/enum for every `$def`, which the
/// promote walker consumes. The wrapper root itself is kept as
/// `VirituraExtensionsRoot` but unused by the engine.
fn generate_viritura_extensions() -> Result<()> {
    let schema_path = workspace_path("packages/format/schemas/viritura-extensions.json");
    let out_path = workspace_path("engine/viritura-engine/src/raw_viritura.rs");
    let schema_copy_path =
        workspace_path("engine/viritura-engine/src/viritura-extensions-schema.json");

    println!("[viritura-ext] Reading schema:  {}", schema_path.display());
    println!("[viritura-ext] Writing types:   {}", out_path.display());
    println!(
        "[viritura-ext] Copying schema:  {}",
        schema_copy_path.display()
    );

    let schema_json = fs::read_to_string(&schema_path)
        .with_context(|| format!("failed to read schema at {}", schema_path.display()))?;
    let schema_value: Value = serde_json::from_str(&schema_json)
        .context("failed to parse viritura-extensions schema as JSON")?;

    let mut wrapped = wrap_defs_as_root(&schema_value)?;
    remove_numeric_constraints(&mut wrapped);
    let root_schema: RootSchema = serde_json::from_value(wrapped)
        .context("synthesised viritura-extensions wrapper isn't a valid RootSchema")?;

    let mut settings = TypeSpaceSettings::default();
    settings.with_struct_builder(false);

    let mut type_space = TypeSpace::new(&settings);
    type_space
        .add_root_schema(root_schema)
        .context("typify failed to process the viritura-extensions schema")?;

    write_typespace(
        &type_space,
        &out_path,
        "// @generated by viritura-codegen from packages/format/schemas/viritura-extensions.json.\n\
         // DO NOT EDIT BY HAND. Re-run `pnpm gen:raw:rust` (or `cargo run -p viritura-codegen`).\n\
         //\n\
         // These types are the structural decoding of Viritura `_x.viritura.*`\n\
         // vendor extensions, before any promotion to the engine model. The\n\
         // wrapper root `VirituraExtensionsRoot` is synthetic and unused by the\n\
         // engine — its only purpose is to force typify to emit each `$def`\n\
         // as a named top-level type.\n\n\
         #![allow(\n    clippy::all,\n    clippy::pedantic,\n    clippy::nursery,\n    clippy::cargo,\n    dead_code,\n    non_camel_case_types,\n    non_snake_case,\n    unused_imports,\n    missing_docs,\n)]\n\n",
    )?;

    fs::copy(&schema_path, &schema_copy_path)
        .with_context(|| format!("failed to copy schema to {}", schema_copy_path.display()))?;

    println!(
        "[viritura-ext] Done. {} bytes written.",
        fs::metadata(&out_path)?.len()
    );
    Ok(())
}

/// Synthesise a wrapper root schema whose properties reference every `$def`
/// in the input schema. This forces typify to generate a named type for
/// each `$def` rather than inlining them.
fn wrap_defs_as_root(schema: &Value) -> Result<Value> {
    let defs = schema
        .get("$defs")
        .and_then(|d| d.as_object())
        .context("viritura-extensions schema is missing top-level `$defs`")?;

    let mut properties = serde_json::Map::with_capacity(defs.len());
    for key in defs.keys() {
        properties.insert(key.clone(), json!({ "$ref": format!("#/$defs/{}", key) }));
    }

    Ok(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "VirituraExtensionsRoot",
        "description":
            "Synthetic root used only to force typify to emit each $def as a named type. \
             This struct is not used by the engine.",
        "type": "object",
        "properties": properties,
        "additionalProperties": false,
        "$defs": defs.clone(),
    }))
}

/// Render a `TypeSpace` to a Rust source file with the supplied header.
fn write_typespace(type_space: &TypeSpace, out_path: &Path, header: &str) -> Result<()> {
    let tokens = type_space.to_stream();
    let file: syn::File =
        syn::parse2(tokens).context("typify output failed to parse as a Rust file")?;
    let formatted = prettyplease::unparse(&file);
    let final_output = format!("{header}{formatted}");
    fs::write(out_path, final_output)
        .with_context(|| format!("failed to write {}", out_path.display()))?;
    Ok(())
}
