/**
 * INSTRUMENT_CATALOG (extras) — keyboards, voices, plucked strings, strings.
 * Concatenated with the primary file in InstrumentCatalog.ts.
 * Split for the lint max-lines threshold.
 */

import type { CatalogInstrument, ClefDef } from "./InstrumentCatalog";

const TREBLE: ClefDef = { sign: "G", staffPosition: -2 };
const BASS: ClefDef = { sign: "F", staffPosition: 2 };
const ALTO: ClefDef = { sign: "C", staffPosition: 0 };
const _TENOR: ClefDef = { sign: "C", staffPosition: 2 };

export const INSTRUMENT_CATALOG_EXTRAS: CatalogInstrument[] = [
  // ═══ KEYBOARDS ═══
  {
    id: "piano",
    name: "Piano",
    shortName: "Pno.",
    family: "keyboards",
    staves: 2,
    clefs: { 1: TREBLE, 2: BASS },
    bracketSymbol: "brace",
    midiProgram: 0,
    scoreOrder: 0,
    rangeLow: 21,
    rangeHigh: 108,
  },
  {
    id: "harpsichord",
    name: "Harpsichord",
    shortName: "Hpsd.",
    family: "keyboards",
    staves: 2,
    clefs: { 1: TREBLE, 2: BASS },
    bracketSymbol: "brace",
    midiProgram: 6,
    scoreOrder: 1,
    rangeLow: 29,
    rangeHigh: 89,
  },
  {
    id: "celesta",
    name: "Celesta",
    shortName: "Cel.",
    family: "keyboards",
    staves: 2,
    clefs: { 1: TREBLE, 2: BASS },
    bracketSymbol: "brace",
    midiProgram: 8,
    scoreOrder: 2,
    rangeLow: 60,
    rangeHigh: 108,
  },
  {
    id: "organ",
    name: "Organ",
    shortName: "Org.",
    family: "keyboards",
    staves: 2,
    clefs: { 1: TREBLE, 2: BASS },
    bracketSymbol: "brace",
    midiProgram: 19,
    scoreOrder: 3,
    rangeLow: 36,
    rangeHigh: 96,
  },
  {
    id: "accordion",
    name: "Accordion",
    shortName: "Acc.",
    family: "keyboards",
    staves: 2,
    clefs: { 1: TREBLE, 2: BASS },
    bracketSymbol: "brace",
    midiProgram: 21,
    scoreOrder: 4,
    rangeLow: 36,
    rangeHigh: 96,
  },

  // ═══ VOICES ═══
  {
    id: "soprano",
    name: "Soprano",
    shortName: "S.",
    family: "voices",
    staves: 1,
    clefs: { 1: TREBLE },
    midiProgram: 52,
    scoreOrder: 0,
    rangeLow: 60,
    rangeHigh: 84,
  },
  {
    id: "mezzo-soprano",
    name: "Mezzo-Soprano",
    shortName: "Ms.",
    family: "voices",
    staves: 1,
    clefs: { 1: TREBLE },
    midiProgram: 52,
    scoreOrder: 1,
    rangeLow: 57,
    rangeHigh: 81,
  },
  {
    id: "alto-voice",
    name: "Alto",
    shortName: "A.",
    family: "voices",
    staves: 1,
    clefs: { 1: TREBLE },
    midiProgram: 52,
    scoreOrder: 2,
    rangeLow: 53,
    rangeHigh: 77,
  },
  {
    id: "tenor-voice",
    name: "Tenor",
    shortName: "T.",
    family: "voices",
    staves: 1,
    clefs: { 1: TREBLE },
    midiProgram: 52,
    scoreOrder: 3,
    rangeLow: 48,
    rangeHigh: 72,
  },
  {
    id: "baritone-voice",
    name: "Baritone",
    shortName: "Bar.",
    family: "voices",
    staves: 1,
    clefs: { 1: BASS },
    midiProgram: 52,
    scoreOrder: 4,
    rangeLow: 45,
    rangeHigh: 69,
  },
  {
    id: "bass-voice",
    name: "Bass",
    shortName: "B.",
    family: "voices",
    staves: 1,
    clefs: { 1: BASS },
    midiProgram: 52,
    scoreOrder: 5,
    rangeLow: 40,
    rangeHigh: 64,
  },

  // ═══ PLUCKED STRINGS ═══
  {
    id: "harp",
    name: "Harp",
    shortName: "Hp.",
    family: "plucked",
    staves: 2,
    clefs: { 1: TREBLE, 2: BASS },
    bracketSymbol: "brace",
    midiProgram: 46,
    scoreOrder: 0,
    rangeLow: 24,
    rangeHigh: 103,
  },
  {
    id: "guitar",
    name: "Guitar",
    shortName: "Gtr.",
    family: "plucked",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 12, staffDistance: 7 },
    midiProgram: 24,
    scoreOrder: 1,
    rangeLow: 40,
    rangeHigh: 88,
  },
  {
    id: "electric-guitar",
    name: "Electric Guitar",
    shortName: "E.Gtr.",
    family: "plucked",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 12, staffDistance: 7 },
    midiProgram: 27,
    scoreOrder: 2,
    rangeLow: 40,
    rangeHigh: 88,
  },
  {
    id: "bass-guitar",
    name: "Bass Guitar",
    shortName: "B.Gtr.",
    family: "plucked",
    staves: 1,
    clefs: { 1: BASS },
    transposition: { halfSteps: 12, staffDistance: 7 },
    midiProgram: 33,
    scoreOrder: 3,
    rangeLow: 28,
    rangeHigh: 67,
  },
  {
    id: "ukulele",
    name: "Ukulele",
    shortName: "Uke.",
    family: "plucked",
    staves: 1,
    clefs: { 1: TREBLE },
    midiProgram: 24,
    scoreOrder: 4,
    rangeLow: 60,
    rangeHigh: 84,
  },
  {
    id: "mandolin",
    name: "Mandolin",
    shortName: "Mand.",
    family: "plucked",
    staves: 1,
    clefs: { 1: TREBLE },
    midiProgram: 24,
    scoreOrder: 5,
    rangeLow: 55,
    rangeHigh: 90,
  },

  // ═══ STRINGS ═══
  {
    id: "violin",
    name: "Violin",
    shortName: "Vln.",
    family: "strings",
    subGroup: "violin",
    staves: 1,
    clefs: { 1: TREBLE },
    midiProgram: 40,
    scoreOrder: 0,
    rangeLow: 55,
    rangeHigh: 103,
  },
  {
    id: "viola",
    name: "Viola",
    shortName: "Vla.",
    family: "strings",
    subGroup: "viola",
    staves: 1,
    clefs: { 1: ALTO },
    midiProgram: 41,
    scoreOrder: 1,
    rangeLow: 48,
    rangeHigh: 93,
  },
  {
    id: "cello",
    name: "Cello",
    shortName: "Vc.",
    family: "strings",
    subGroup: "cello",
    staves: 1,
    clefs: { 1: BASS },
    midiProgram: 42,
    scoreOrder: 2,
    rangeLow: 36,
    rangeHigh: 84,
  },
  {
    id: "double-bass",
    name: "Double Bass",
    shortName: "Cb.",
    family: "strings",
    subGroup: "double-bass",
    staves: 1,
    clefs: { 1: BASS },
    transposition: { halfSteps: 12, staffDistance: 7 },
    midiProgram: 43,
    scoreOrder: 3,
    rangeLow: 28,
    rangeHigh: 67,
  },
];
