/**
 * INSTRUMENT_CATALOG (primary) — woodwinds, brass, percussion.
 * Concatenated with the extras file in InstrumentCatalog.ts.
 * Split for the lint max-lines threshold.
 */

import type { CatalogInstrument, ClefDef } from "./InstrumentCatalog";
import { FULL_DRUM_KIT_COMPONENTS, ORCHESTRAL_PERCUSSION_COMPONENTS } from "./percussionPresets";

// ─── Clef shorthands ───────────────────────────────────────────────
const TREBLE: ClefDef = { sign: "G", staffPosition: -2 };
const BASS: ClefDef = { sign: "F", staffPosition: 2 };
const _ALTO: ClefDef = { sign: "C", staffPosition: 0 };
const _TENOR: ClefDef = { sign: "C", staffPosition: 2 };
const PERCUSSION_CLEF: ClefDef = { sign: "P", staffPosition: 0 };

export const INSTRUMENT_CATALOG_PRIMARY: CatalogInstrument[] = [
  // ═══ WOODWINDS ═══
  {
    id: "wind.flutes.flute.piccolo",
    name: "Piccolo",
    shortName: "Picc.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: -12, staffDistance: -7 },
    midiProgram: 72,
    scoreOrder: 0,
    rangeLow: 74,
    rangeHigh: 108,
  },
  {
    id: "wind.flutes.flute",
    name: "Flute",
    shortName: "Fl.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: TREBLE },
    midiProgram: 73,
    scoreOrder: 1,
    rangeLow: 60,
    rangeHigh: 96,
  },
  {
    id: "wind.flutes.flute.alto",
    name: "Alto Flute",
    shortName: "A.Fl.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 5, staffDistance: 3 },
    midiProgram: 73,
    scoreOrder: 2,
    rangeLow: 55,
    rangeHigh: 91,
  },
  {
    id: "wind.reed.oboe",
    name: "Oboe",
    shortName: "Ob.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: TREBLE },
    midiProgram: 68,
    scoreOrder: 3,
    rangeLow: 58,
    rangeHigh: 91,
  },
  {
    id: "wind.reed.english-horn",
    name: "English Horn",
    shortName: "E.Hn.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 7, staffDistance: 4 },
    midiProgram: 69,
    scoreOrder: 4,
    rangeLow: 52,
    rangeHigh: 84,
  },
  {
    id: "wind.reed.clarinet.bflat",
    name: "Clarinet in B♭",
    shortName: "Cl.",
    baseName: "Clarinet",
    baseShortName: "Cl.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 2, staffDistance: 1 },
    midiProgram: 71,
    scoreOrder: 5,
    rangeLow: 50,
    rangeHigh: 94,
  },
  {
    id: "wind.reed.clarinet.a",
    pickerDefaultId: "wind.reed.clarinet.bflat",
    name: "Clarinet in A",
    shortName: "Cl.",
    baseName: "Clarinet",
    baseShortName: "Cl.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 3, staffDistance: 2 },
    midiProgram: 71,
    scoreOrder: 5,
    rangeLow: 49,
    rangeHigh: 93,
  },
  {
    id: "wind.reed.clarinet.eflat",
    pickerName: "Piccolo Clarinet",
    name: "Clarinet in E♭",
    shortName: "Cl.",
    baseName: "Clarinet",
    baseShortName: "Cl.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: -3, staffDistance: -2 },
    midiProgram: 71,
    scoreOrder: 4,
    rangeLow: 53,
    rangeHigh: 97,
  },
  {
    id: "wind.reed.clarinet.bass",
    name: "Bass Clarinet",
    shortName: "B.Cl.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 14, staffDistance: 8 },
    midiProgram: 71,
    scoreOrder: 7,
    rangeLow: 38,
    rangeHigh: 77,
  },
  {
    id: "wind.reed.bassoon",
    name: "Bassoon",
    shortName: "Bsn.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: BASS },
    midiProgram: 70,
    scoreOrder: 8,
    rangeLow: 34,
    rangeHigh: 75,
  },
  {
    id: "wind.reed.contrabassoon",
    name: "Contrabassoon",
    shortName: "Cbsn.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: BASS },
    transposition: { halfSteps: 12, staffDistance: 7 },
    midiProgram: 70,
    scoreOrder: 9,
    rangeLow: 22,
    rangeHigh: 57,
  },
  {
    id: "wind.reed.saxophone.soprano",
    name: "Soprano Saxophone",
    shortName: "S.Sax.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 2, staffDistance: 1 },
    midiProgram: 64,
    scoreOrder: 10,
    rangeLow: 56,
    rangeHigh: 90,
  },
  {
    id: "wind.reed.saxophone.alto",
    name: "Alto Saxophone",
    shortName: "A.Sax.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 9, staffDistance: 5 },
    midiProgram: 65,
    scoreOrder: 11,
    rangeLow: 49,
    rangeHigh: 83,
  },
  {
    id: "wind.reed.saxophone.tenor",
    name: "Tenor Saxophone",
    shortName: "T.Sax.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 14, staffDistance: 8 },
    midiProgram: 66,
    scoreOrder: 12,
    rangeLow: 44,
    rangeHigh: 78,
  },
  {
    id: "wind.reed.saxophone.baritone",
    name: "Baritone Saxophone",
    shortName: "B.Sax.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 21, staffDistance: 12 },
    midiProgram: 67,
    scoreOrder: 13,
    rangeLow: 36,
    rangeHigh: 71,
  },
  {
    id: "wind.flutes.recorder",
    name: "Recorder",
    shortName: "Rec.",
    family: "woodwinds",
    staves: 1,
    clefs: { 1: TREBLE },
    midiProgram: 74,
    scoreOrder: 0,
    rangeLow: 60,
    rangeHigh: 96,
  },

  // ═══ BRASS ═══
  {
    id: "brass.french-horn",
    name: "Horn in F",
    shortName: "Hn.",
    baseName: "Horn",
    baseShortName: "Hn.",
    family: "brass",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 7, staffDistance: 4 },
    midiProgram: 60,
    scoreOrder: 0,
    rangeLow: 35,
    rangeHigh: 77,
  },
  {
    id: "brass.trumpet.bflat",
    name: "Trumpet in B♭",
    shortName: "Tpt.",
    baseName: "Trumpet",
    baseShortName: "Tpt.",
    family: "brass",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 2, staffDistance: 1 },
    midiProgram: 56,
    scoreOrder: 1,
    rangeLow: 54,
    rangeHigh: 89,
  },
  {
    id: "brass.trumpet.c",
    pickerDefaultId: "brass.trumpet.bflat",
    name: "Trumpet in C",
    shortName: "Tpt.",
    baseName: "Trumpet",
    baseShortName: "Tpt.",
    family: "brass",
    staves: 1,
    clefs: { 1: TREBLE },
    midiProgram: 56,
    scoreOrder: 1,
    rangeLow: 52,
    rangeHigh: 87,
  },
  {
    id: "brass.cornet",
    name: "Cornet in B♭",
    shortName: "Cnt.",
    baseName: "Cornet",
    baseShortName: "Cnt.",
    family: "brass",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 2, staffDistance: 1 },
    midiProgram: 56,
    scoreOrder: 2,
    rangeLow: 54,
    rangeHigh: 87,
  },
  {
    id: "brass.flugelhorn",
    name: "Flugelhorn",
    shortName: "Flg.",
    family: "brass",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: 2, staffDistance: 1 },
    midiProgram: 59,
    scoreOrder: 3,
    rangeLow: 54,
    rangeHigh: 84,
  },
  {
    id: "brass.trombone",
    name: "Trombone",
    shortName: "Tbn.",
    family: "brass",
    staves: 1,
    clefs: { 1: BASS },
    midiProgram: 57,
    scoreOrder: 4,
    rangeLow: 40,
    rangeHigh: 79,
  },
  {
    id: "brass.trombone.bass",
    name: "Bass Trombone",
    shortName: "B.Tbn.",
    family: "brass",
    staves: 1,
    clefs: { 1: BASS },
    midiProgram: 57,
    scoreOrder: 5,
    rangeLow: 33,
    rangeHigh: 72,
  },
  {
    id: "brass.euphonium",
    name: "Euphonium",
    shortName: "Euph.",
    family: "brass",
    staves: 1,
    clefs: { 1: BASS },
    midiProgram: 58,
    scoreOrder: 6,
    rangeLow: 36,
    rangeHigh: 77,
  },
  {
    id: "brass.tuba",
    name: "Tuba",
    shortName: "Tba.",
    family: "brass",
    staves: 1,
    clefs: { 1: BASS },
    midiProgram: 58,
    scoreOrder: 7,
    rangeLow: 28,
    rangeHigh: 65,
  },

  // ═══ PERCUSSION ═══
  {
    id: "drum.group.set",
    name: "Drum Kit",
    shortName: "D.Kit",
    family: "percussion",
    staves: 1,
    clefs: { 1: PERCUSSION_CLEF },
    midiProgram: 0, // routed to GM channel 10 by playback engine
    scoreOrder: -1, // appears before timpani in percussion section
    rangeLow: 35,
    rangeHigh: 81,
    kit: [...FULL_DRUM_KIT_COMPONENTS],
  },
  {
    id: "drum.group",
    name: "Orchestral Percussion",
    shortName: "Perc.",
    family: "percussion",
    staves: 1,
    clefs: { 1: PERCUSSION_CLEF },
    midiProgram: 0, // routed to GM channel 10 by playback engine
    scoreOrder: -0.5, // between the drum kit and timpani
    rangeLow: 35,
    rangeHigh: 81,
    kit: [...ORCHESTRAL_PERCUSSION_COMPONENTS],
  },
  {
    id: "drum.timpani",
    name: "Timpani",
    shortName: "Timp.",
    family: "percussion",
    staves: 1,
    clefs: { 1: BASS },
    midiProgram: 47,
    scoreOrder: 0,
    rangeLow: 40,
    rangeHigh: 60,
  },
  {
    id: "drum.snare-drum",
    name: "Snare Drum",
    shortName: "S.Dr.",
    family: "percussion",
    staves: 1,
    staffLines: { 1: 1 },
    clefs: { 1: PERCUSSION_CLEF },
    midiProgram: 0,
    unpitchedDrum: 38, // GM Acoustic Snare
    scoreOrder: 1,
    rangeLow: 38,
    rangeHigh: 40,
  },
  {
    id: "drum.bass-drum",
    name: "Bass Drum",
    shortName: "B.Dr.",
    family: "percussion",
    staves: 1,
    staffLines: { 1: 1 },
    clefs: { 1: PERCUSSION_CLEF },
    midiProgram: 0,
    unpitchedDrum: 36, // GM Bass Drum 1
    scoreOrder: 2,
    rangeLow: 35,
    rangeHigh: 36,
  },
  {
    id: "metal.cymbal.clash",
    name: "Cymbals",
    shortName: "Cym.",
    family: "percussion",
    staves: 1,
    staffLines: { 1: 1 },
    clefs: { 1: PERCUSSION_CLEF },
    midiProgram: 0,
    unpitchedDrum: 49, // GM Crash Cymbal 1
    unpitchedDrumNotehead: "x",
    scoreOrder: 3,
    rangeLow: 49,
    rangeHigh: 57,
  },
  {
    id: "metal.triangle",
    name: "Triangle",
    shortName: "Tri.",
    family: "percussion",
    staves: 1,
    staffLines: { 1: 1 },
    clefs: { 1: PERCUSSION_CLEF },
    midiProgram: 0,
    unpitchedDrum: 81, // GM Open Triangle
    unpitchedDrumNotehead: "x",
    scoreOrder: 4,
    rangeLow: 81,
    rangeHigh: 81,
  },
  {
    id: "drum.tambourine",
    name: "Tambourine",
    shortName: "Tamb.",
    family: "percussion",
    staves: 1,
    staffLines: { 1: 1 },
    clefs: { 1: PERCUSSION_CLEF },
    midiProgram: 0,
    unpitchedDrum: 54, // GM Tambourine
    scoreOrder: 5,
    rangeLow: 54,
    rangeHigh: 54,
  },
  {
    id: "pitched-percussion.glockenspiel",
    name: "Glockenspiel",
    shortName: "Glock.",
    family: "percussion",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: -24, staffDistance: -14 },
    midiProgram: 9,
    scoreOrder: 6,
    rangeLow: 79,
    rangeHigh: 108,
  },
  {
    id: "pitched-percussion.xylophone",
    name: "Xylophone",
    shortName: "Xyl.",
    family: "percussion",
    staves: 1,
    clefs: { 1: TREBLE },
    transposition: { halfSteps: -12, staffDistance: -7 },
    midiProgram: 13,
    scoreOrder: 7,
    rangeLow: 65,
    rangeHigh: 108,
  },
  {
    id: "pitched-percussion.vibraphone",
    name: "Vibraphone",
    shortName: "Vib.",
    family: "percussion",
    staves: 1,
    clefs: { 1: TREBLE },
    midiProgram: 11,
    scoreOrder: 8,
    rangeLow: 53,
    rangeHigh: 89,
  },
  {
    id: "pitched-percussion.marimba",
    name: "Marimba",
    shortName: "Mar.",
    family: "percussion",
    staves: 1,
    clefs: { 1: TREBLE },
    midiProgram: 12,
    scoreOrder: 9,
    rangeLow: 45,
    rangeHigh: 96,
  },
  {
    id: "pitched-percussion.tubular-bells",
    name: "Tubular Bells",
    shortName: "T.B.",
    family: "percussion",
    staves: 1,
    clefs: { 1: TREBLE },
    midiProgram: 14,
    scoreOrder: 10,
    rangeLow: 60,
    rangeHigh: 77,
  },
];
