import { describe, expect, it } from "vitest";
import type { NoteEvent } from "@viritura/core";
import type { ClipboardSelection } from "../../commands/clipboardCommands";
import { MUSESCORE_STAFF_LIST_MIME, readMuseScoreClipboard, writeMuseScoreStaffList } from ".";

// MuseScore v4.7.5, pinned source contract (not a reader/writer round-trip oracle):
// https://github.com/musescore/MuseScore/tree/3654226c2e99289916916953a98e585a3d3b315a
// src/engraving/dom/select.cpp: tick is source-absolute; voiceOffset is selection-relative ticks / 1920.
// src/engraving/rw/write/writer.cpp:278-287: each Staff resets track to id * 4; only curTick carries.
// src/engraving/rw/write/twrite.cpp: writeVoiceMove emits relative deltas against absolute segment ticks.
// src/engraving/rw/read460/read460.cpp:370-408: start at tick 0, offset by destinationTick - root.tick,
// and reset the track to Staff.id * 4 at EVERY Staff boundary.
// These minimal XML literals are hand-authored from that contract, never generated by our writer.

const USER_STAFF_LIST = `<?xml version="1.0" encoding="UTF-8"?>
<StaffList version="4.70" tick="0/1" len="4/4" staff="22" staves="1">
  <Staff id="22">
    <voiceOffset><voice id="0">0</voice></voiceOffset>
    <Harmony><harmonyInfo><name>m</name><root>14</root></harmonyInfo></Harmony>
    <Dynamic><subtype>mf</subtype><velocity>96</velocity></Dynamic>
    <Chord><durationType>eighth</durationType><Note><pitch>75</pitch><tpc>11</tpc></Note></Chord>
    <Chord><durationType>eighth</durationType><Note><pitch>79</pitch><tpc>15</tpc></Note></Chord>
    <Chord><durationType>eighth</durationType><Note><pitch>84</pitch><tpc>14</tpc></Note></Chord>
    <Chord><durationType>eighth</durationType><Note><pitch>86</pitch><tpc>16</tpc></Note></Chord>
    <Chord><durationType>eighth</durationType><Note><pitch>87</pitch><tpc>11</tpc></Note></Chord>
    <Chord><durationType>eighth</durationType><Note><pitch>86</pitch><tpc>16</tpc></Note></Chord>
    <Chord><durationType>eighth</durationType><Note><pitch>84</pitch><tpc>14</tpc></Note></Chord>
    <Chord><durationType>eighth</durationType><Note><pitch>79</pitch><tpc>15</tpc></Note></Chord>
  </Staff>
</StaffList>`;

const SPARSE_STAFF_LIST = `<StaffList version="4.70" tick="3/8" len="5/8" staff="22" staves="6">
  <Staff id="22">
    <voiceOffset><voice id="1">240</voice><voice id="3">720</voice></voiceOffset>
    <location><voices>1</voices><fractions>1/2</fractions></location>
    <Chord><durationType>eighth</durationType><Note><pitch>60</pitch><tpc>14</tpc></Note></Chord>
    <location><voices>2</voices><fractions>1/8</fractions></location>
    <Chord><durationType>quarter</durationType><Note><pitch>62</pitch><tpc>16</tpc></Note></Chord>
  </Staff>
  <Staff id="24">
    <voiceOffset><voice id="2">480</voice><voice id="3">0</voice></voiceOffset>
    <location><voices>2</voices><fractions>-3/8</fractions></location>
    <Chord><durationType>quarter</durationType><Note><pitch>64</pitch><tpc>18</tpc></Note></Chord>
    <location><voices>1</voices><fractions>-1/2</fractions></location>
    <Chord><durationType>eighth</durationType><Note><pitch>65</pitch><tpc>13</tpc></Note></Chord>
  </Staff>
  <Staff id="27">
    <voiceOffset><voice id="0">0</voice><voice id="2">240</voice></voiceOffset>
    <location><fractions>-1/8</fractions></location>
    <Chord><durationType>eighth</durationType><Note><pitch>55</pitch><tpc>15</tpc></Note></Chord>
    <location><voices>2</voices></location>
    <Chord><durationType>quarter</durationType><dots>1</dots><Note><pitch>57</pitch><tpc>17</tpc></Note></Chord>
    <location><fractions>1/16</fractions></location>
    <Chord><durationType>16th</durationType><Note><pitch>59</pitch><tpc>19</tpc></Note></Chord>
  </Staff>
</StaffList>`;

const REWOUND_ANNOTATIONS = `<StaffList version="4.70" tick="3/8" len="1/2" staff="22" staves="1">
  <Staff id="22">
    <voiceOffset><voice id="1">0</voice><voice id="3">240</voice></voiceOffset>
    <location><voices>1</voices><fractions>3/8</fractions></location>
    <Chord><durationType>half</durationType><Note><pitch>60</pitch><tpc>14</tpc></Note></Chord>
    <location><fractions>-3/8</fractions></location>
    <Harmony><harmonyInfo><name>m</name><root>14</root></harmonyInfo></Harmony>
    <Dynamic><subtype>mf</subtype><velocity>96</velocity></Dynamic>
    <location><voices>2</voices></location>
    <Chord><durationType>quarter</durationType><Note><pitch>64</pitch><tpc>18</tpc></Note></Chord>
  </Staff>
</StaffList>`;

const SHIFTED_RHYTHM = `<StaffList version="4.70" tick="1/1" len="3/4" staff="22" staves="1">
  <Staff id="22">
    <voiceOffset><voice id="0">0</voice></voiceOffset>
    <location><fractions>1/1</fractions></location>
    <Rest><durationType>eighth</durationType></Rest>
    <location><fractions>1/8</fractions></location>
    <Chord><durationType>eighth</durationType><acciaccatura/><Note><pitch>60</pitch><tpc>14</tpc></Note></Chord>
    <Tuplet><normalNotes>2</normalNotes><actualNotes>3</actualNotes><baseNote>eighth</baseNote></Tuplet>
    <Chord><durationType>eighth</durationType><Note><pitch>62</pitch><tpc>16</tpc></Note></Chord>
    <Chord><durationType>eighth</durationType><Note><pitch>64</pitch><tpc>18</tpc></Note></Chord>
    <Chord><durationType>eighth</durationType><Note><pitch>65</pitch><tpc>13</tpc></Note></Chord>
    <endTuplet/>
    <Rest><durationType>quarter</durationType></Rest>
  </Staff>
</StaffList>`;

const TWO_STAFF_QUARTERS = `<StaffList version="4.70" tick="0/1" len="1/4" staff="0" staves="2">
  <Staff id="0">
    <voiceOffset><voice id="0">0</voice></voiceOffset>
    <Chord><durationType>quarter</durationType><Note><pitch>60</pitch><tpc>14</tpc></Note></Chord>
  </Staff>
  <Staff id="1">
    <voiceOffset><voice id="0">0</voice></voiceOffset>
    <location><fractions>-1/4</fractions></location>
    <Chord><durationType>quarter</durationType><Note><pitch>55</pitch><tpc>15</tpc></Note></Chord>
  </Staff>
</StaffList>`;

const NORMALIZED_SPARSE_STAFF_LIST = `<StaffList version="4.70" tick="0/1" len="5/8" staff="0" staves="6">
  <Staff id="0">
    <voiceOffset><voice id="1">240</voice><voice id="3">720</voice></voiceOffset>
    <location><voices>1</voices><fractions>1/8</fractions></location>
    <Chord><durationType>eighth</durationType><Note><pitch>60</pitch><tpc>14</tpc></Note></Chord>
    <location><voices>2</voices><fractions>1/8</fractions></location>
    <Chord><durationType>quarter</durationType><Note><pitch>62</pitch><tpc>16</tpc></Note></Chord>
  </Staff>
  <Staff id="2">
    <voiceOffset><voice id="2">480</voice><voice id="3">0</voice></voiceOffset>
    <location><voices>2</voices><fractions>-3/8</fractions></location>
    <Chord><durationType>quarter</durationType><Note><pitch>64</pitch><tpc>18</tpc></Note></Chord>
    <location><voices>1</voices><fractions>-1/2</fractions></location>
    <Chord><durationType>eighth</durationType><Note><pitch>65</pitch><tpc>13</tpc></Note></Chord>
  </Staff>
  <Staff id="5">
    <voiceOffset><voice id="0">0</voice><voice id="2">240</voice></voiceOffset>
    <location><fractions>-1/8</fractions></location>
    <Chord><durationType>eighth</durationType><Note><pitch>55</pitch><tpc>15</tpc></Note></Chord>
    <location><voices>2</voices></location>
    <Chord><durationType>quarter</durationType><dots>1</dots><Note><pitch>57</pitch><tpc>17</tpc></Note></Chord>
    <location><fractions>1/16</fractions></location>
    <Chord><durationType>16th</durationType><Note><pitch>59</pitch><tpc>19</tpc></Note></Chord>
  </Staff>
</StaffList>`;

function note(
  step: NonNullable<NoteEvent["notes"]>[number]["pitch"]["step"],
  octave: NonNullable<NoteEvent["notes"]>[number]["pitch"]["octave"],
  base: NoteEvent["duration"]["base"] = "quarter",
  alter?: number,
): NoteEvent {
  return {
    type: "event",
    duration: { base },
    notes: [{ pitch: { step, octave, ...(alter === undefined ? {} : { alter }) } }],
  };
}

function withoutGeneratedIds(value: unknown): unknown {
  return JSON.parse(JSON.stringify(value, (key, item: unknown) => (key === "id" ? undefined : item)));
}

function compactXml(xml: string): string {
  return xml.trim().replace(/>\s+</g, "><");
}

function selection(overrides: Partial<ClipboardSelection>): ClipboardSelection {
  return {
    events: [note("C", 4)],
    timeSignature: { count: 4, unit: 4 },
    keySignature: { fifths: 0 },
    partIndex: 22,
    measureIndex: 1,
    sequenceIndex: 0,
    eventIndex: 0,
    ...overrides,
  };
}

function expectCmAndMf(parsed: ReturnType<typeof readMuseScoreClipboard>, offset: [number, number]): void {
  expect(parsed.chordSymbols).toHaveLength(1);
  expect(parsed.chordSymbols?.[0]).toMatchObject({
    partOffset: 0,
    staffOffset: 0,
    measureOffset: 0,
    offset,
    chordSymbol: { root: { step: "C" }, quality: "minor", position: { fraction: [0, 1] } },
  });
  expect(parsed.dynamics).toHaveLength(1);
  expect(parsed.dynamics?.[0]).toMatchObject({
    staffOffset: 0,
    measureOffset: 0,
    offset,
    dynamic: {
      type: "immediate",
      value: "mf",
      playbackVelocity: 96,
      position: { fraction: [0, 1] },
    },
  });
}

describe("MuseScore v4.7.5 pinned source-absolute StaffList reader contract", () => {
  it.each(["0/1", "1/1", "3/8"])(
    "normalizes the supplied eight-note Cm/mf literal moved to source tick %s",
    (sourceTick) => {
      // Moving the source selection changes root.tick and ONLY the initial absolute location.
      // The 1/1 case is the user's unchanged melody copied from bar 2 in 4/4.
      const xml = USER_STAFF_LIST.replace('tick="0/1"', `tick="${sourceTick}"`).replace(
        "</voiceOffset>",
        `</voiceOffset>${sourceTick === "0/1" ? "" : `<location><fractions>${sourceTick}</fractions></location>`}`,
      );
      const parsed = readMuseScoreClipboard(xml, MUSESCORE_STAFF_LIST_MIME);
      expect(withoutGeneratedIds(parsed.content)).toEqual([
        note("E", 5, "eighth", -1),
        note("G", 5, "eighth"),
        note("C", 6, "eighth"),
        note("D", 6, "eighth"),
        note("E", 6, "eighth", -1),
        note("D", 6, "eighth"),
        note("C", 6, "eighth"),
        note("G", 5, "eighth"),
      ]);
      expect(parsed.tracks).toBeUndefined();
      expectCmAndMf(parsed, [0, 1]);
    },
  );

  it("retains a lone nonzero voice even with zero lead-in and no other tracks", () => {
    const xml = `<StaffList version="4.70" tick="1/1" len="1/4" staff="22" staves="1">
      <Staff id="22">
        <voiceOffset><voice id="2">0</voice></voiceOffset>
        <location><voices>2</voices><fractions>1/1</fractions></location>
        <Chord><durationType>quarter</durationType><Note><pitch>70</pitch><tpc>12</tpc></Note></Chord>
      </Staff>
    </StaffList>`;
    const parsed = readMuseScoreClipboard(xml, MUSESCORE_STAFF_LIST_MIME);
    expect(withoutGeneratedIds(parsed)).toEqual({
      content: [note("B", 4, "quarter", -1)],
      tracks: [{ partOffset: 0, staffOffset: 0, voiceIndex: 2, content: [note("B", 4, "quarter", -1)] }],
    });
  });

  it("resets voices, not time, across three sparse Staff ids starting at 22", () => {
    // Absolute starts: staff 22 voices 1/3 = 1/2, 3/4; staff 24 voices 2/3 = 5/8, 3/8;
    // staff 27 voices 0/2 = 3/8, 1/2. Subtract root.tick = 3/8 exactly once.
    // Boundaries rewind 1 -> 5/8 and 1/2 -> 3/8, while voices restart from zero.
    const parsed = readMuseScoreClipboard(SPARSE_STAFF_LIST, MUSESCORE_STAFF_LIST_MIME);
    expect(withoutGeneratedIds(parsed.tracks)).toEqual([
      { partOffset: 0, staffOffset: 0, voiceIndex: 1, leadIn: [1, 8], content: [note("C", 4, "eighth")] },
      { partOffset: 0, staffOffset: 0, voiceIndex: 3, leadIn: [3, 8], content: [note("D", 4)] },
      { partOffset: 0, staffOffset: 2, voiceIndex: 2, leadIn: [1, 4], content: [note("E", 4)] },
      { partOffset: 0, staffOffset: 2, voiceIndex: 3, content: [note("F", 4, "eighth")] },
      { partOffset: 0, staffOffset: 5, voiceIndex: 0, content: [note("G", 3, "eighth")] },
      {
        partOffset: 0,
        staffOffset: 5,
        voiceIndex: 2,
        leadIn: [1, 8],
        content: [
          { ...note("A", 3), duration: { base: "quarter", dots: 1 } },
          { type: "space", duration: [1, 16] },
          note("B", 3, "16th"),
        ],
      },
    ]);
    expect(withoutGeneratedIds(parsed.content)).toEqual([note("C", 4, "eighth")]);
    expect(parsed.chordSymbols).toBeUndefined();
    expect(parsed.dynamics).toBeUndefined();
  });

  it("subtracts the source tick from annotations after a rewind without moving the next voice", () => {
    // A half note ends at 7/8, then -3/8 locates Cm/mf and voice 3 at 1/2:
    // the captured offset is 1/2 - 3/8 = 1/8, not 1/2 or the previous voice's end.
    const parsed = readMuseScoreClipboard(REWOUND_ANNOTATIONS, MUSESCORE_STAFF_LIST_MIME);
    expect(withoutGeneratedIds(parsed.tracks)).toEqual([
      { partOffset: 0, staffOffset: 0, voiceIndex: 1, content: [note("C", 4, "half")] },
      { partOffset: 0, staffOffset: 0, voiceIndex: 3, leadIn: [1, 8], content: [note("E", 4)] },
    ]);
    expectCmAndMf(parsed, [1, 8]);
  });

  it.each(["1/1", "3/8"])("normalizes rests, spaces, grace notes, and a complete triplet at tick %s", (sourceTick) => {
    const xml = SHIFTED_RHYTHM.replace('tick="1/1"', `tick="${sourceTick}"`).replace(
      "<fractions>1/1</fractions>",
      `<fractions>${sourceTick}</fractions>`,
    );
    const parsed = readMuseScoreClipboard(xml, MUSESCORE_STAFF_LIST_MIME);
    expect(withoutGeneratedIds(parsed)).toEqual({
      content: [
        { type: "event", duration: { base: "eighth" }, rest: {} },
        { type: "space", duration: [1, 8] },
        { type: "grace", graceType: "stealFollowing", slash: true, content: [note("C", 4, "eighth")] },
        {
          type: "tuplet",
          inner: { duration: { base: "eighth" }, multiple: 3 },
          outer: { duration: { base: "eighth" }, multiple: 2 },
          content: [note("D", 4, "eighth"), note("E", 4, "eighth"), note("F", 4, "eighth")],
        },
        { type: "event", duration: { base: "quarter" }, rest: {} },
      ],
    });
  });

  it("does not reinterpret an unshifted absolute location as selection-relative at a nonzero root tick", () => {
    const xml = USER_STAFF_LIST.replace('tick="0/1"', 'tick="1/1"');
    expect(() => readMuseScoreClipboard(xml, MUSESCORE_STAFF_LIST_MIME)).toThrow("before the selection start");
  });
});

describe("MuseScore v4.7.5 pinned canonical StaffList writer contract", () => {
  it.each([0, 1])(
    "writes two single-voice quarter-note staves from measure %s exactly, normalized to tick 0",
    (measureIndex) => {
      const result = writeMuseScoreStaffList(
        selection({
          measureIndex,
          tracks: [
            { partOffset: 0, staffOffset: 0, voiceIndex: 0, content: [note("C", 4)] },
            { partOffset: 1, staffOffset: 1, voiceIndex: 0, content: [note("G", 3)] },
          ],
        }),
      );
      // Staff 1 starts at voice 0 without a <staves> move, but time still needs -1/4.
      expect(result).toEqual({ xml: compactXml(TWO_STAFF_QUARTERS) });
    },
  );

  it("writes sparse staves, within-staff relative voices, lead-ins, and carried rewinds exactly", () => {
    const result = writeMuseScoreStaffList(
      selection({
        tracks: [
          { partOffset: 0, staffOffset: 0, voiceIndex: 1, leadIn: [1, 8], content: [note("C", 4, "eighth")] },
          { partOffset: 0, staffOffset: 0, voiceIndex: 3, leadIn: [3, 8], content: [note("D", 4)] },
          { partOffset: 1, staffOffset: 2, voiceIndex: 2, leadIn: [1, 4], content: [note("E", 4)] },
          { partOffset: 1, staffOffset: 2, voiceIndex: 3, content: [note("F", 4, "eighth")] },
          { partOffset: 2, staffOffset: 5, voiceIndex: 0, content: [note("G", 3, "eighth")] },
          {
            partOffset: 2,
            staffOffset: 5,
            voiceIndex: 2,
            leadIn: [1, 8],
            content: [
              { ...note("A", 3), duration: { base: "quarter", dots: 1 } },
              { type: "space", duration: [1, 16] },
              note("B", 3, "16th"),
            ],
          },
        ],
      }),
    );
    // The independent literal forbids both a cross-Staff <staves> delta and inherited voices.
    // Within each Staff, <voices>2</voices> still means +2, not "set voice 2".
    expect(result).toEqual({ xml: compactXml(NORMALIZED_SPARSE_STAFF_LIST) });
  });

  it("writes a lone nonzero voice's lead-in in ticks and its first location in whole-note fractions", () => {
    const expected = `<StaffList version="4.70" tick="0/1" len="3/8" staff="0" staves="1">
      <Staff id="0">
        <voiceOffset><voice id="2">240</voice></voiceOffset>
        <location><voices>2</voices><fractions>1/8</fractions></location>
        <Chord><durationType>quarter</durationType><Note><pitch>70</pitch><tpc>12</tpc></Note></Chord>
      </Staff>
    </StaffList>`;
    const result = writeMuseScoreStaffList(
      selection({
        events: [note("B", 4, "quarter", -1)],
        tracks: [
          { partOffset: 0, staffOffset: 0, voiceIndex: 2, leadIn: [1, 8], content: [note("B", 4, "quarter", -1)] },
        ],
      }),
    );
    expect(result).toEqual({ xml: compactXml(expected) });
  });
});
